# Generated by Django 3.2.9 on 2021-11-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='color',
            field=models.CharField(choices=[('White', 'oq'), ('Black', 'qora'), ('Blue', 'kok'), ('other', 'Boshqa')], max_length=150, verbose_name='Rangi: '),
        ),
        migrations.AlterField(
            model_name='transport',
            name='condition',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ('Eski', 'Eski'), ('Ortacha', 'Ortacha'), ('Ishlatip olsa boladi', 'Ishlatip olsa boladi'), ('Vashee Zor', 'Vashee Zor')], max_length=150, verbose_name='Avtomobil holati'),
        ),
    ]
